spring:
  application:
    name: security-test-repo
  security:
    user:
     name: user
     password: password

  datasource:
    url: jdbc:postgresql://localhost:5450/test_user_db
    driver-class-name: org.postgresql.Driver
    username: user
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect